import Sidebar from "@/components/shared/sidebar";

export const metadata = {
  title: "Next Dashboard",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return (
    <div>
      <Sidebar></Sidebar>
      {children}
    </div>
  );
};

export default layout;
